# -*- coding: utf-8 -*-
"""gear_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mb7vKZCzO3h2PAFmypAiT301d4WsqwrU
"""

import streamlit as st
import joblib
import pandas as pd

# Load trained model
model = joblib.load("dtc_model.pkl")

st.title("Machine Condition  Prediction")

# Inputs (matching your new dataset columns exactly)
load = st.number_input("Load_%", value=0.0)
temperature = st.number_input("Temperature_C", value=0.0)
vibration = st.number_input("Vibration_mm_s", value=0.0)
oil_level = st.number_input("Oil_Level_%", value=0.0)

# Create dataframe EXACTLY like training data
input_data = pd.DataFrame({
    "Load_%": [load],
    "Temperature_C": [temperature],
    "Vibration_mm_s": [vibration],
    "Oil_Level_%": [oil_level]
})

if st.button("Predict"):
   if prediction == 1:
    st.error("Machine Failure ⚠️")
else:
    st.success("Machine Normal ✅")